require('lazy').setup({
  -- require 'custom.plugins.themes.github-theme',
  require 'custom.plugins.themes.vscode',

  require 'custom.plugins.flash',
  require 'custom.plugins.bufferline',
  require 'custom.plugins.diffview',
  require 'custom.plugins.neogit',
  require 'custom.plugins.neoscroll',
  require 'custom.plugins.scrollbar',
  require 'custom.plugins.fidget',
  require 'custom.plugins.colorizer',
  require 'custom.plugins.treesitter-textobjects',
  require 'custom.plugins.guess-indent',
  require 'custom.plugins.noice',
  require 'custom.plugins.github-theme',
  require 'custom.plugins.rainbow-delimiters',

  require 'kickstart.plugins.gitsigns',
  require 'kickstart.plugins.which-key',
  require 'kickstart.plugins.telescope',
  require 'kickstart.plugins.lspconfig',
  require 'kickstart.plugins.conform',
  require 'kickstart.plugins.blink-cmp',
  require 'kickstart.plugins.todo-comments',
  require 'kickstart.plugins.mini',
  require 'kickstart.plugins.treesitter',
  -- require 'kickstart.plugins.debug',
  require 'kickstart.plugins.indent_line',
  -- require 'kickstart.plugins.lint',
  require 'kickstart.plugins.autopairs',
  -- require 'kickstart.plugins.neo-tree',
}, {
  ui = {
    icons = vim.g.have_nerd_font and {} or {
      cmd = '⌘',
      config = '🛠',
      event = '📅',
      ft = '📂',
      init = '⚙',
      keys = '🗝',
      plugin = '🔌',
      runtime = '💻',
      require = '🌙',
      source = '📄',
      start = '🚀',
      task = '📌',
      lazy = '💤 ',
    },
  },
})
