vim.pack.add { 'https://github.com/folke/which-key.nvim' }
require('which-key').setup {
  preset = 'helix',
  sort = { 'local', 'manual', 'order', 'group', 'alphanum', 'mod' },
  show_help = false,
  delay = 1000,
  triggers = { { '<auto>', mode = 'nixsotc' }, { 's', mode = 'n' } },
  icons = { mappings = vim.g.have_nerd_font },
  spec = {
    { '<leader>p', group = '[p]age' },
    { '<leader>w', group = '[w]indow' },
    { '<leader>d', group = '[d]ebug' },
    { '<leader>s', group = '[s]witch' },
    { '<leader>t', group = '[t]est' },
    { '<leader>g', group = '[g]it' },
    { '<leader>h', group = '[h]unk', mode = { 'n', 'v' } },
    { '<leader>f', group = '[f]ind' },
    { '<leader>a', group = '[a]i', mode = { 'n', 'x' } },
    { 's', group = '[s]urround', mode = { 'n', 'x' } },
    { 'sa', desc = '[a]dd', mode = { 'n', 'x' } },
    { 'sd', desc = '[d]elete', mode = { 'n' } },
    { 'sr', desc = '[r]eplace', mode = { 'n' } },
    { 'sh', desc = '[h]ighlight', mode = { 'n' } },
    { 'sp', desc = 'find prev', mode = { 'n' } },
    { 'sn', desc = 'find next', mode = { 'n' } },
  },
}
